In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import roc_curve
from sklearn.metrics  import roc_auc_score
from sklearn.tree import DecisionTreeClassifier 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_score

In [8]:
cancerset=load_breast_cancer()
df_cancer=pd.DataFrame(cancerset.data,columns=cancerset.feature_names)
pd.set_option('display.max_rows', None)
df_cancer['target']=pd.DataFrame(data=cancerset.target)
x=df_cancer.drop(['target'],axis=1)
y=df_cancer['target']
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.30,random_state=45)
lg=LogisticRegression()
gnb=GaussianNB()
svc=SVC()
dtc=DecisionTreeClassifier()
knn=KNeighborsClassifier()

model=[lg,gnb,svc,dtc,knn]
for m in model:
    m.fit(train_x,train_y)
    m.score(train_x,train_y)
    predm=m.predict(test_x)
    print("Accuracy_score:",m,'is')
    print(accuracy_score(test_y,predm))
    print(classification_report(test_y,predm))
    print('\n')

Accuracy_score: LogisticRegression() is
0.9473684210526315
              precision    recall  f1-score   support

           0       0.98      0.87      0.92        61
           1       0.93      0.99      0.96       110

    accuracy                           0.95       171
   macro avg       0.96      0.93      0.94       171
weighted avg       0.95      0.95      0.95       171



Accuracy_score: GaussianNB() is
0.935672514619883
              precision    recall  f1-score   support

           0       0.96      0.85      0.90        61
           1       0.92      0.98      0.95       110

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171



Accuracy_score: SVC() is
0.9122807017543859
              precision    recall  f1-score   support

           0       0.98      0.77      0.86        61
           1       0.89      0.99      0.94       110

    accuracy             

scaling techniqus

In [10]:
from sklearn.preprocessing import StandardScaler

In [15]:
st=StandardScaler()
x=st.fit_transform(x)
x

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [16]:
xf=pd.DataFrame(data=x)

In [17]:
xf

0         1         2         3         4         5         6   \
0    1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   
1    1.829821 -0.353632  1.685955  1.908708 -0.826962 -0.487072 -0.023846   
2    1.579888  0.456187  1.566503  1.558884  0.942210  1.052926  1.363478   
3   -0.768909  0.253732 -0.592687 -0.764464  3.283553  3.402909  1.915897   
4    1.750297 -1.151816  1.776573  1.826229  0.280372  0.539340  1.371011   
5   -0.476375 -0.835335 -0.387148 -0.505650  2.237421  1.244335  0.866302   
6    1.170908  0.160649  1.138125  1.095295 -0.123136  0.088295  0.300072   
7   -0.118517  0.358450 -0.072867 -0.218965  1.604049  1.140102  0.061026   
8   -0.320167  0.588830 -0.184080 -0.384207  2.201839  1.684010  1.219096   
9   -0.473535  1.105439 -0.329482 -0.509063  1.582699  2.563358  1.738872   
10   0.537556  0.919273  0.442011  0.406453 -1.017686 -0.713542 -0.700684   
11   0.469393 -0.325708  0.479082  0.358672  0.052642  0.471115  0.134849   
12   1.432201  1.282296  1.665360  1.331355  0.073992  2.680858  1.477729   
13   0.489274  1.084495  0.483201  0.363507 -0.878913 -0.078478  0.132840   
14  -0.112836  0.772668  0.067180 -0.217827  1.191289  2.368158  1.556825   
15   0.117215  1.919912  0.196105  0.011123  1.248222  1.045345  0.942887   
16   0.156977  0.195555  0.114137  0.084216  0.164372 -0.612909 -0.186433   
17   0.568798  0.323544  0.664438  0.409297  1.468835  1.854573  1.047093   
18   1.613970  0.665623  1.566503  1.720997  0.138753 -0.031099  0.742007   
19  -0.166799 -1.147162 -0.185728 -0.251957  0.101747 -0.436850 -0.278210   
20  -0.297446 -0.833008 -0.261106 -0.383638  0.792763  0.429422 -0.541362   
21  -1.313080 -1.593959 -1.302806 -1.083572  0.429819 -0.747086 -0.743748   
22   0.344426 -1.170433  0.433773  0.140814  0.778530  2.068725  1.492795   
23   1.997389  0.872732  1.863073  2.130548 -0.148044 -0.040575  0.262407   
24   0.716485  0.486439  0.742699  0.710203  1.120124  0.783815  0.799760   
25   0.855652 -0.672441  0.989840  0.733241  1.582699  2.335941  1.683630   
26   0.128576  0.521345  0.224115 -0.028694  0.643316  1.562720  0.674211   
27   1.273153  0.223480  1.241101  1.248876 -0.139504  0.042812  0.755818   
28   0.333066  1.391668  0.429654  0.220449  0.842579  1.238650  0.998129   
29   0.977778 -0.986595  0.948650  0.853831  0.150139  0.215270  0.124931   
30   1.278833  1.354435  1.352314  1.231812  0.714481  1.598728  1.796625   
31  -0.649623 -0.137215 -0.578271 -0.609460  1.034726  0.895628  0.414323   
32   0.821570  1.091476  0.858032  0.695130  1.660981  0.857725  1.919664   
33   1.460602  1.670916  1.480004  1.442275 -0.167259  1.280343  0.965486   
34   0.568798 -0.328035  0.619129  0.433188  0.543684  0.977120  0.585070   
35   0.742046  0.535307  0.746818  0.610375 -0.018523  0.554502  0.577537   
36   0.034851  0.565559  0.068416 -0.062255  0.133059  0.103456  0.541128   
37  -0.311646 -0.202373 -0.385500 -0.372831 -0.464730 -1.263703 -0.793214   
38   0.245021  1.375378  0.147089  0.124887 -0.177222 -1.005016 -0.813805   
39  -0.183840  0.356123 -0.147009 -0.272150  0.372887  0.400995  0.219721   
40  -0.195201  0.532980 -0.238451 -0.261342 -1.048999 -0.834452 -0.724413   
41  -0.902396  0.479458 -0.826648 -0.807125  1.874478  0.330874  0.195866   
42   1.403799  1.284623  1.496480  1.277317 -0.394988  2.172958  1.530460   
43  -0.240643  0.230461 -0.191495 -0.311967  0.550801  0.744016  0.121415   
44  -0.271884  0.586503 -0.269756 -0.350931  0.055489  0.006804 -0.077958   
45   1.284513 -0.393193  1.307005  1.197683  0.963560  1.217803  1.363478   
46  -1.684571 -0.570050 -1.658278 -1.288347 -0.737294 -0.851130 -0.915500   
47  -0.271884 -0.146523 -0.246689 -0.342115  1.383436  0.355511  0.424367   
48  -0.589980 -1.084331 -0.573740 -0.584717  0.479635 -0.254348 -0.287249   
49  -0.181000  0.700529 -0.208383 -0.267030 -0.629123 -0.518531 -0.518386   
50  -0.672344  0.537634 -0.710491 -0.645580 -0.710963 -1.036286 -0.906837   
51  -0.

In [21]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.30,random_state=45)
lg=LogisticRegression()
gnb=GaussianNB()
svc=SVC()
dtc=DecisionTreeClassifier()
knn=KNeighborsClassifier()

model=[lg,gnb,svc,dtc,knn]
for m in model:
    m.fit(train_x,train_y)
    m.score(train_x,train_y)
    predm=m.predict(test_x)
    print("Accuracy_score:",m,'is')
    print(accuracy_score(test_y,predm))
    print(confusion_matrix(test_y,predm))
    print(classification_report(test_y,predm))
    print('\n')

Accuracy_score: LogisticRegression() is
0.9883040935672515
[[ 59   2]
 [  0 110]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98        61
           1       0.98      1.00      0.99       110

    accuracy                           0.99       171
   macro avg       0.99      0.98      0.99       171
weighted avg       0.99      0.99      0.99       171



Accuracy_score: GaussianNB() is
0.9415204678362573
[[ 53   8]
 [  2 108]]
              precision    recall  f1-score   support

           0       0.96      0.87      0.91        61
           1       0.93      0.98      0.96       110

    accuracy                           0.94       171
   macro avg       0.95      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



Accuracy_score: SVC() is
0.9707602339181286
[[ 57   4]
 [  1 109]]
              precision    recall  f1-score   support

           0       0.98      0.93      0.96        61
          

In [22]:
from sklearn.preprocessing import MinMaxScaler
st=MinMaxScaler()
x=st.fit_transform(x)
x

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [23]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.30,random_state=45)
lg=LogisticRegression()
gnb=GaussianNB()
svc=SVC()
dtc=DecisionTreeClassifier()
knn=KNeighborsClassifier()

model=[lg,gnb,svc,dtc,knn]
for m in model:
    m.fit(train_x,train_y)
    m.score(train_x,train_y)
    predm=m.predict(test_x)
    print("Accuracy_score:",m,'is')
    print(accuracy_score(test_y,predm))
    print(confusion_matrix(test_y,predm))
    print(classification_report(test_y,predm))
    print('\n')

Accuracy_score: LogisticRegression() is
0.9707602339181286
[[ 56   5]
 [  0 110]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        61
           1       0.96      1.00      0.98       110

    accuracy                           0.97       171
   macro avg       0.98      0.96      0.97       171
weighted avg       0.97      0.97      0.97       171



Accuracy_score: GaussianNB() is
0.9415204678362573
[[ 53   8]
 [  2 108]]
              precision    recall  f1-score   support

           0       0.96      0.87      0.91        61
           1       0.93      0.98      0.96       110

    accuracy                           0.94       171
   macro avg       0.95      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



Accuracy_score: SVC() is
0.9883040935672515
[[ 59   2]
 [  0 110]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98        61
          