In [2]:
import numpy

In [4]:
numpy.array([1,2,3,4,5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
numpy.array([11,12,13,14,1,5])

array([11, 12, 13, 14,  1,  5])

In [5]:
import numpy as np

In [6]:
a=np.array([11,4,5,6,7,8,9])

In [7]:
a

array([11,  4,  5,  6,  7,  8,  9])

In [8]:
a.shape

(7,)

In [9]:
b=np.array([11,4,5,9,7,8,10,45,15,16])

In [10]:
b

array([11,  4,  5,  9,  7,  8, 10, 45, 15, 16])

In [11]:
b.shape

(10,)

In [12]:
a=np.array([[1,2],[2,3]])

In [13]:
a.shape

(2, 2)

In [14]:
a

array([[1, 2],
       [2, 3]])

In [15]:
b=np.array([[3,2,5],[1,7,9]])

In [16]:
b

array([[3, 2, 5],
       [1, 7, 9]])

In [17]:
b.shape

(2, 3)

In [18]:
c=np.array([[1,2,4],[2,3,6],[4,6,7]])

In [20]:
c

array([[1, 2, 4],
       [2, 3, 6],
       [4, 6, 7]])

In [21]:
c=np.array([[1,2,4],[2,3,6]])

In [22]:
c

array([[1, 2, 4],
       [2, 3, 6]])

In [23]:
c.shape

(2, 3)

In [25]:
c=np.array([[1,2],[2,3],[4,5]])

In [26]:
c.shape

(3, 2)

In [27]:
c=np.array([[1,2],[2,3],[4,5],[5,6],[4,3]])

In [28]:
c.shape

(5, 2)

In [29]:
g=np.array([[1,2],[2,3],[4,5]])
g

array([[1, 2],
       [2, 3],
       [4, 5]])

In [31]:
g.shape

(3, 2)

In [32]:
g.reshape(2,3)

array([[1, 2, 2],
       [3, 4, 5]])

In [36]:
c=np.array([[1,2],[2,3],[4,5]])
c.min()
c.max()

5

In [37]:
b.shape

(2, 3)

In [38]:
c.size

6

In [39]:
c.itemsize

4

In [40]:
c.dtype

dtype('int32')

In [41]:
c.min()

1

In [42]:
c.max()

5

In [43]:
c.data

In [80]:
a=np.array([[1,2],[3,4],[5,6]],dtype='float64')


In [81]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [82]:

a,a.dtype

(array([[1., 2.],
        [3., 4.],
        [5., 6.]]),
 dtype('float64'))

In [46]:
a.itemsize

8

In [47]:
a.shape

(3, 2)

In [48]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [61]:
a.ndim

2

In [62]:
y=np.arange(15)

In [18]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [64]:
a=x.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
a=x.reshape(5,3)

In [66]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [67]:
x=np.arange(25)
a=x.reshape(5,5)

In [69]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
x=np.arange(25).reshape(5,5)

In [70]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
a.ndim

2

In [72]:
a.dtype

dtype('int32')

In [83]:
type(a)

numpy.ndarray

In [75]:
a=np.array([[1,2],[3,4],[5,6]],dtype='float32')
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [73]:
import numpy as np
b=np.array([[1,2],[3,4],[5,6]],dtype='float32')

In [74]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [36]:
print(b.ravel())#to get all   data

[1. 2. 3. 4. 5. 6.]


In [38]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [42]:
np.arange(0,25,5)

array([ 0,  5, 10, 15, 20])

In [43]:
b=np.arange(12).reshape(4,3)

In [44]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Broadcasting in Numpy

In [47]:
a=np.array([11,4,5,6,7,8,9])
b=np.array([18,13,19,10,45,15,16])
a*b


array([198,  52,  95,  60, 315, 120, 144])

In [84]:
a=np.array([11,4,5,6,7,8,9])
b=2
a*b

array([22,  8, 10, 12, 14, 16, 18])

In [91]:
b=np.random.random([2,3])

In [93]:
b

array([[0.30699959, 0.52797561, 0.83136614],
       [0.41160449, 0.77193889, 0.01866753]])

In [51]:
c=np.ones([2,3])

In [52]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
d=b+c

In [54]:
d

array([[1.86846013, 1.90020276, 1.82574632],
       [1.60155058, 1.58748807, 1.27254759]])

In [55]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [94]:
np.exp(b)

array([[1.35934041, 1.69549649, 2.29645387],
       [1.5092374 , 2.16395787, 1.01884286]])

In [95]:
np.sqrt(b)

array([[0.55407544, 0.7266193 , 0.91179281],
       [0.6415641 , 0.87860053, 0.13662918]])

indexing,slicing and iterating

In [104]:
a=np.arange(20)

In [105]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [100]:
a[2]
a[2:7]

array([2, 3, 4, 5, 6])

In [101]:
a[2]

2

In [103]:
a[-2]

8

In [106]:
a=np.arange(20)

In [107]:
a[:5]

array([0, 1, 2, 3, 4])

In [108]:
a[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [110]:
d=np.array([np.nan,1,3,4])
d

array([nan,  1.,  3.,  4.])

In [114]:
np.random.rand(2,3)

array([[0.54654281, 0.15563902, 0.51342695],
       [0.99159578, 0.05799162, 0.90306511]])

In [115]:
np.random.randn(2,3)

array([[ 0.13659069, -1.7164527 , -0.17490198],
       [ 1.02486619,  0.2866765 ,  1.19972895]])

In [7]:
b=np.arange(3)

In [8]:
b

array([0, 1, 2])

In [9]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [10]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [11]:
c=np.array([1,2,3])
np.add(b,c)

array([1, 3, 5])